version: '2.0'
services:
  api-user:
    container_name: user-service
    image: fabian/user-service
    build: .
    ports:
      - "2002:2002"
    volumes:
      - .:/usr/src/app
      - /src/app/node_modules
    command: npm run dev
    links:
      - mongo
    depends_on:
      - "mongo"
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
